runtime: nodejs18

instance_class: F2

env_variables:
  NODE_OPTIONS: --openssl-legacy-provider

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /
    static_dir: build
